SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Events` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `DeviceId` VARCHAR(45) NULL DEFAULT NULL,
  `Action` VARCHAR(45) NULL DEFAULT NULL,
  `Zone` VARCHAR(45) NULL DEFAULT NULL,
  `Value` VARCHAR(45) NULL DEFAULT NULL,
  `TimeStamp` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `Readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Readings` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `ReadingType` VARCHAR(255) NULL DEFAULT NULL,
  `DeviceId` VARCHAR(45) NULL DEFAULT NULL,
  `Value` VARCHAR(45) NULL DEFAULT NULL,
  `TimeStamp` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;